name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Configuração do Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalação de Dependências
      run: npm install

    - name: Execução dos Testes
      run: npm test

    - name: Construir o Projeto
      run: |
        # Comandos para construir o projeto, por exemplo, compilação de código, minificação de arquivos, etc.
        echo "Construindo o projeto..."
